import { spawn, execFileSync } from 'child_process';
import { adapters } from './adapters/index.js';

/**
 * Check which adapters have their binary available on PATH.
 */
export function availableAdapters() {
  return adapters.filter(adapter => {
    try {
      execFileSync('which', [adapter.binary], { stdio: 'ignore' });
      return true;
    } catch {
      return false;
    }
  });
}

function buildPrompt(digest, additionalFiles = {}) {
  let extra = '';
  if (Object.keys(additionalFiles).length > 0) {
    extra = '\n\n## Additional Files (fetched to fill gaps you identified)\n';
    for (const [path, content] of Object.entries(additionalFiles)) {
      extra += `\n### ${path}\n\`\`\`\n${content}\n\`\`\`\n`;
    }
    extra += '\nYou now have complete context. Produce the final analysis.';
  }

  const missingNotice = Object.keys(additionalFiles).length > 0
    ? '' // second pass — no need to ask for more files
    : `
- criticalMissing (optional): If any files that are essential to accurately describe
  the architecture, entry point, or core logic appear in the tree but are absent or
  truncated in the digest, list their repo-relative paths here (max 5, source code only).
  Leave empty or omit if you have sufficient context.`;

  const criticalMissingField = Object.keys(additionalFiles).length > 0
    ? ''
    : `\n  "criticalMissing": ["path/to/file"]`;

  return `You are the developer who built this repository. Write from your perspective — first person, explaining how and why you'd rebuild this project from scratch. Be specific: reference actual files, functions, and patterns from the codebase.

Be ruthlessly concise. Return a single JSON object, no preamble, no markdown fences, just raw JSON.

## Required JSON schema

{
  "overview": "string — 2-3 sentences, first person. What I built, what problem it solves, and my core approach.",
  "architecture": [
    { "name": "string — component/layer name", "role": "string — first person, one sentence: what this does and why I need it" }
  ],
  "reconstruction": [
    "string — one step of how I'd rebuild this from scratch, in build order. What I'd write and why at this stage."
  ],
  "e2eFlow": "string — compact ASCII diagram tracing the primary entry point through the system. Use \\n for newlines.",
  "decisions": [
    "string — first person: a specific design choice I made and why (e.g. 'I used X instead of Y because...')"
  ]${criticalMissingField}
}

## Rules

- overview: 2-3 sentences. First person. Specific to THIS repo.
- architecture: 4-6 components MAX. One sentence each. First person.
- reconstruction: 5-8 steps in chronological build order. Each step explains what you'd build AND why it comes at that stage. First person.
- e2eFlow: 10-15 lines MAX. ASCII diagram only, no prose.
- decisions: 3-5 items MAX. Must explain the "why", not just state what was chosen. First person.${missingNotice}
- Return ONLY the JSON object.

## Repository context (generated by gitingest)

${digest}${extra}`;
}

/**
 * Run the analysis using the given adapter.
 *
 * @param {string} digest          - gitingest output (LLM-ready repo context)
 * @param {object} adapter         - one of the adapters from src/adapters/
 * @param {string} model           - model ID to pass to the adapter
 * @param {function} onChunk       - called with accumulated text as chunks arrive
 * @param {object} additionalFiles - { path: content } from a gap-fill fetch (second pass)
 * @returns {Promise<string>}      - full analysis JSON string
 */
export async function analyze(digest, adapter, model, onChunk, additionalFiles = {}) {
  const prompt = buildPrompt(digest, additionalFiles);
  const args = adapter.args(model);

  return new Promise((resolve, reject) => {
    const child = spawn(adapter.binary, args, {
      stdio: ['pipe', 'pipe', 'pipe'],
      cwd: process.env.HOME || process.cwd(),
    });

    let accumulated = '';
    let stderrBuf = '';

    child.stdout.on('data', (chunk) => {
      accumulated += chunk.toString();
      onChunk?.(accumulated);
    });

    child.stderr.on('data', (chunk) => {
      stderrBuf += chunk.toString();
    });

    child.on('error', (err) => {
      if (err.code === 'ENOENT') {
        reject(new Error(`'${adapter.binary}' not found on PATH`));
      } else {
        reject(err);
      }
    });

    child.on('close', (code) => {
      const final = adapter.transformOutput(accumulated);

      if (!final) {
        const detail = stderrBuf.trim()
          ? `\n\nstderr:\n${stderrBuf.trim()}`
          : '\n\n(no stderr output)';
        reject(new Error(`${adapter.hint} exited with code ${code} and produced no output${detail}`));
        return;
      }

      if (code !== 0 && stderrBuf.trim()) {
        process.stderr.write(`\n[warn] ${adapter.hint} stderr:\n${stderrBuf.trim()}\n`);
      }

      resolve(final);
    });

    child.stdin.write(prompt, 'utf-8');
    child.stdin.end();
  });
}
